// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: fleet.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PlateNumber   string                 `protobuf:"bytes,2,opt,name=plate_number,json=plateNumber,proto3" json:"plate_number,omitempty"`
	OperatorName  string                 `protobuf:"bytes,3,opt,name=operator_name,json=operatorName,proto3" json:"operator_name,omitempty"`
	Capacity      int32                  `protobuf:"varint,4,opt,name=capacity,proto3" json:"capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BusResponse) Reset() {
	*x = BusResponse{}
	mi := &file_fleet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusResponse) ProtoMessage() {}

func (x *BusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusResponse.ProtoReflect.Descriptor instead.
func (*BusResponse) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{0}
}

func (x *BusResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BusResponse) GetPlateNumber() string {
	if x != nil {
		return x.PlateNumber
	}
	return ""
}

func (x *BusResponse) GetOperatorName() string {
	if x != nil {
		return x.OperatorName
	}
	return ""
}

func (x *BusResponse) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

type CreateBusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlateNumber   string                 `protobuf:"bytes,1,opt,name=plate_number,json=plateNumber,proto3" json:"plate_number,omitempty"`
	OperatorName  string                 `protobuf:"bytes,2,opt,name=operator_name,json=operatorName,proto3" json:"operator_name,omitempty"`
	Capacity      int32                  `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBusRequest) Reset() {
	*x = CreateBusRequest{}
	mi := &file_fleet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBusRequest) ProtoMessage() {}

func (x *CreateBusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBusRequest.ProtoReflect.Descriptor instead.
func (*CreateBusRequest) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBusRequest) GetPlateNumber() string {
	if x != nil {
		return x.PlateNumber
	}
	return ""
}

func (x *CreateBusRequest) GetOperatorName() string {
	if x != nil {
		return x.OperatorName
	}
	return ""
}

func (x *CreateBusRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

type ListBusesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBusesRequest) Reset() {
	*x = ListBusesRequest{}
	mi := &file_fleet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBusesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBusesRequest) ProtoMessage() {}

func (x *ListBusesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBusesRequest.ProtoReflect.Descriptor instead.
func (*ListBusesRequest) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{2}
}

func (x *ListBusesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListBusesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListBusesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buses         []*BusResponse         `protobuf:"bytes,1,rep,name=buses,proto3" json:"buses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBusesResponse) Reset() {
	*x = ListBusesResponse{}
	mi := &file_fleet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBusesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBusesResponse) ProtoMessage() {}

func (x *ListBusesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBusesResponse.ProtoReflect.Descriptor instead.
func (*ListBusesResponse) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{3}
}

func (x *ListBusesResponse) GetBuses() []*BusResponse {
	if x != nil {
		return x.Buses
	}
	return nil
}

type RouteResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Origin                string                 `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination           string                 `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	DistanceKm            int32                  `protobuf:"varint,4,opt,name=distance_km,json=distanceKm,proto3" json:"distance_km,omitempty"`
	EstimatedDurationMins int32                  `protobuf:"varint,5,opt,name=estimated_duration_mins,json=estimatedDurationMins,proto3" json:"estimated_duration_mins,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RouteResponse) Reset() {
	*x = RouteResponse{}
	mi := &file_fleet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteResponse) ProtoMessage() {}

func (x *RouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteResponse.ProtoReflect.Descriptor instead.
func (*RouteResponse) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{4}
}

func (x *RouteResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RouteResponse) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *RouteResponse) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *RouteResponse) GetDistanceKm() int32 {
	if x != nil {
		return x.DistanceKm
	}
	return 0
}

func (x *RouteResponse) GetEstimatedDurationMins() int32 {
	if x != nil {
		return x.EstimatedDurationMins
	}
	return 0
}

type CreateRouteRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Origin                string                 `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination           string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	DistanceKm            int32                  `protobuf:"varint,3,opt,name=distance_km,json=distanceKm,proto3" json:"distance_km,omitempty"`
	EstimatedDurationMins int32                  `protobuf:"varint,4,opt,name=estimated_duration_mins,json=estimatedDurationMins,proto3" json:"estimated_duration_mins,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CreateRouteRequest) Reset() {
	*x = CreateRouteRequest{}
	mi := &file_fleet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRouteRequest) ProtoMessage() {}

func (x *CreateRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRouteRequest.ProtoReflect.Descriptor instead.
func (*CreateRouteRequest) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{5}
}

func (x *CreateRouteRequest) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *CreateRouteRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *CreateRouteRequest) GetDistanceKm() int32 {
	if x != nil {
		return x.DistanceKm
	}
	return 0
}

func (x *CreateRouteRequest) GetEstimatedDurationMins() int32 {
	if x != nil {
		return x.EstimatedDurationMins
	}
	return 0
}

type ListRoutesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoutesRequest) Reset() {
	*x = ListRoutesRequest{}
	mi := &file_fleet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoutesRequest) ProtoMessage() {}

func (x *ListRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoutesRequest.ProtoReflect.Descriptor instead.
func (*ListRoutesRequest) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{6}
}

func (x *ListRoutesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRoutesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListRoutesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routes        []*RouteResponse       `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoutesResponse) Reset() {
	*x = ListRoutesResponse{}
	mi := &file_fleet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoutesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoutesResponse) ProtoMessage() {}

func (x *ListRoutesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoutesResponse.ProtoReflect.Descriptor instead.
func (*ListRoutesResponse) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{7}
}

func (x *ListRoutesResponse) GetRoutes() []*RouteResponse {
	if x != nil {
		return x.Routes
	}
	return nil
}

type ScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RouteId       string                 `protobuf:"bytes,2,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	BusId         string                 `protobuf:"bytes,3,opt,name=bus_id,json=busId,proto3" json:"bus_id,omitempty"`
	DepartureTime string                 `protobuf:"bytes,4,opt,name=departure_time,json=departureTime,proto3" json:"departure_time,omitempty"`
	ArrivalTime   string                 `protobuf:"bytes,5,opt,name=arrival_time,json=arrivalTime,proto3" json:"arrival_time,omitempty"`
	Price         float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleResponse) Reset() {
	*x = ScheduleResponse{}
	mi := &file_fleet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleResponse) ProtoMessage() {}

func (x *ScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleResponse.ProtoReflect.Descriptor instead.
func (*ScheduleResponse) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{8}
}

func (x *ScheduleResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScheduleResponse) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *ScheduleResponse) GetBusId() string {
	if x != nil {
		return x.BusId
	}
	return ""
}

func (x *ScheduleResponse) GetDepartureTime() string {
	if x != nil {
		return x.DepartureTime
	}
	return ""
}

func (x *ScheduleResponse) GetArrivalTime() string {
	if x != nil {
		return x.ArrivalTime
	}
	return ""
}

func (x *ScheduleResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ScheduleResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouteId       string                 `protobuf:"bytes,1,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	BusId         string                 `protobuf:"bytes,2,opt,name=bus_id,json=busId,proto3" json:"bus_id,omitempty"`
	DepartureTime string                 `protobuf:"bytes,3,opt,name=departure_time,json=departureTime,proto3" json:"departure_time,omitempty"`
	ArrivalTime   string                 `protobuf:"bytes,4,opt,name=arrival_time,json=arrivalTime,proto3" json:"arrival_time,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScheduleRequest) Reset() {
	*x = CreateScheduleRequest{}
	mi := &file_fleet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScheduleRequest) ProtoMessage() {}

func (x *CreateScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScheduleRequest.ProtoReflect.Descriptor instead.
func (*CreateScheduleRequest) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{9}
}

func (x *CreateScheduleRequest) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *CreateScheduleRequest) GetBusId() string {
	if x != nil {
		return x.BusId
	}
	return ""
}

func (x *CreateScheduleRequest) GetDepartureTime() string {
	if x != nil {
		return x.DepartureTime
	}
	return ""
}

func (x *CreateScheduleRequest) GetArrivalTime() string {
	if x != nil {
		return x.ArrivalTime
	}
	return ""
}

func (x *CreateScheduleRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateScheduleRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListSchedulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSchedulesRequest) Reset() {
	*x = ListSchedulesRequest{}
	mi := &file_fleet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchedulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchedulesRequest) ProtoMessage() {}

func (x *ListSchedulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchedulesRequest.ProtoReflect.Descriptor instead.
func (*ListSchedulesRequest) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{10}
}

func (x *ListSchedulesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListSchedulesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListSchedulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schedules     []*ScheduleResponse    `protobuf:"bytes,1,rep,name=schedules,proto3" json:"schedules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSchedulesResponse) Reset() {
	*x = ListSchedulesResponse{}
	mi := &file_fleet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchedulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchedulesResponse) ProtoMessage() {}

func (x *ListSchedulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchedulesResponse.ProtoReflect.Descriptor instead.
func (*ListSchedulesResponse) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{11}
}

func (x *ListSchedulesResponse) GetSchedules() []*ScheduleResponse {
	if x != nil {
		return x.Schedules
	}
	return nil
}

type SeatLayoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BusId         string                 `protobuf:"bytes,2,opt,name=bus_id,json=busId,proto3" json:"bus_id,omitempty"`
	SeatNumber    string                 `protobuf:"bytes,3,opt,name=seat_number,json=seatNumber,proto3" json:"seat_number,omitempty"`
	IsWindow      bool                   `protobuf:"varint,4,opt,name=is_window,json=isWindow,proto3" json:"is_window,omitempty"`
	IsAisle       bool                   `protobuf:"varint,5,opt,name=is_aisle,json=isAisle,proto3" json:"is_aisle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeatLayoutResponse) Reset() {
	*x = SeatLayoutResponse{}
	mi := &file_fleet_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeatLayoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatLayoutResponse) ProtoMessage() {}

func (x *SeatLayoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatLayoutResponse.ProtoReflect.Descriptor instead.
func (*SeatLayoutResponse) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{12}
}

func (x *SeatLayoutResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SeatLayoutResponse) GetBusId() string {
	if x != nil {
		return x.BusId
	}
	return ""
}

func (x *SeatLayoutResponse) GetSeatNumber() string {
	if x != nil {
		return x.SeatNumber
	}
	return ""
}

func (x *SeatLayoutResponse) GetIsWindow() bool {
	if x != nil {
		return x.IsWindow
	}
	return false
}

func (x *SeatLayoutResponse) GetIsAisle() bool {
	if x != nil {
		return x.IsAisle
	}
	return false
}

type CreateSeatLayoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BusId         string                 `protobuf:"bytes,1,opt,name=bus_id,json=busId,proto3" json:"bus_id,omitempty"`
	SeatNumber    string                 `protobuf:"bytes,2,opt,name=seat_number,json=seatNumber,proto3" json:"seat_number,omitempty"`
	IsWindow      bool                   `protobuf:"varint,3,opt,name=is_window,json=isWindow,proto3" json:"is_window,omitempty"`
	IsAisle       bool                   `protobuf:"varint,4,opt,name=is_aisle,json=isAisle,proto3" json:"is_aisle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSeatLayoutRequest) Reset() {
	*x = CreateSeatLayoutRequest{}
	mi := &file_fleet_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSeatLayoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSeatLayoutRequest) ProtoMessage() {}

func (x *CreateSeatLayoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSeatLayoutRequest.ProtoReflect.Descriptor instead.
func (*CreateSeatLayoutRequest) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{13}
}

func (x *CreateSeatLayoutRequest) GetBusId() string {
	if x != nil {
		return x.BusId
	}
	return ""
}

func (x *CreateSeatLayoutRequest) GetSeatNumber() string {
	if x != nil {
		return x.SeatNumber
	}
	return ""
}

func (x *CreateSeatLayoutRequest) GetIsWindow() bool {
	if x != nil {
		return x.IsWindow
	}
	return false
}

func (x *CreateSeatLayoutRequest) GetIsAisle() bool {
	if x != nil {
		return x.IsAisle
	}
	return false
}

type ListBusSeatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BusId         string                 `protobuf:"bytes,1,opt,name=bus_id,json=busId,proto3" json:"bus_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBusSeatsRequest) Reset() {
	*x = ListBusSeatsRequest{}
	mi := &file_fleet_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBusSeatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBusSeatsRequest) ProtoMessage() {}

func (x *ListBusSeatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBusSeatsRequest.ProtoReflect.Descriptor instead.
func (*ListBusSeatsRequest) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{14}
}

func (x *ListBusSeatsRequest) GetBusId() string {
	if x != nil {
		return x.BusId
	}
	return ""
}

type ListBusSeatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seats         []*SeatLayoutResponse  `protobuf:"bytes,1,rep,name=seats,proto3" json:"seats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBusSeatsResponse) Reset() {
	*x = ListBusSeatsResponse{}
	mi := &file_fleet_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBusSeatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBusSeatsResponse) ProtoMessage() {}

func (x *ListBusSeatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBusSeatsResponse.ProtoReflect.Descriptor instead.
func (*ListBusSeatsResponse) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{15}
}

func (x *ListBusSeatsResponse) GetSeats() []*SeatLayoutResponse {
	if x != nil {
		return x.Seats
	}
	return nil
}

type GetManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduleId    string                 `protobuf:"bytes,1,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManifestRequest) Reset() {
	*x = GetManifestRequest{}
	mi := &file_fleet_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestRequest) ProtoMessage() {}

func (x *GetManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestRequest.ProtoReflect.Descriptor instead.
func (*GetManifestRequest) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{16}
}

func (x *GetManifestRequest) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

type GetManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduleId    string                 `protobuf:"bytes,1,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	OperatorName  string                 `protobuf:"bytes,2,opt,name=operator_name,json=operatorName,proto3" json:"operator_name,omitempty"`
	PlateNumber   string                 `protobuf:"bytes,3,opt,name=plate_number,json=plateNumber,proto3" json:"plate_number,omitempty"`
	BookedSeats   []string               `protobuf:"bytes,4,rep,name=booked_seats,json=bookedSeats,proto3" json:"booked_seats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManifestResponse) Reset() {
	*x = GetManifestResponse{}
	mi := &file_fleet_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestResponse) ProtoMessage() {}

func (x *GetManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestResponse.ProtoReflect.Descriptor instead.
func (*GetManifestResponse) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{17}
}

func (x *GetManifestResponse) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *GetManifestResponse) GetOperatorName() string {
	if x != nil {
		return x.OperatorName
	}
	return ""
}

func (x *GetManifestResponse) GetPlateNumber() string {
	if x != nil {
		return x.PlateNumber
	}
	return ""
}

func (x *GetManifestResponse) GetBookedSeats() []string {
	if x != nil {
		return x.BookedSeats
	}
	return nil
}

var File_fleet_proto protoreflect.FileDescriptor

const file_fleet_proto_rawDesc = "" +
	"\n" +
	"\vfleet.proto\x12\x05fleet\"\x81\x01\n" +
	"\vBusResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fplate_number\x18\x02 \x01(\tR\vplateNumber\x12#\n" +
	"\roperator_name\x18\x03 \x01(\tR\foperatorName\x12\x1a\n" +
	"\bcapacity\x18\x04 \x01(\x05R\bcapacity\"v\n" +
	"\x10CreateBusRequest\x12!\n" +
	"\fplate_number\x18\x01 \x01(\tR\vplateNumber\x12#\n" +
	"\roperator_name\x18\x02 \x01(\tR\foperatorName\x12\x1a\n" +
	"\bcapacity\x18\x03 \x01(\x05R\bcapacity\"@\n" +
	"\x10ListBusesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"=\n" +
	"\x11ListBusesResponse\x12(\n" +
	"\x05buses\x18\x01 \x03(\v2\x12.fleet.BusResponseR\x05buses\"\xb2\x01\n" +
	"\rRouteResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06origin\x18\x02 \x01(\tR\x06origin\x12 \n" +
	"\vdestination\x18\x03 \x01(\tR\vdestination\x12\x1f\n" +
	"\vdistance_km\x18\x04 \x01(\x05R\n" +
	"distanceKm\x126\n" +
	"\x17estimated_duration_mins\x18\x05 \x01(\x05R\x15estimatedDurationMins\"\xa7\x01\n" +
	"\x12CreateRouteRequest\x12\x16\n" +
	"\x06origin\x18\x01 \x01(\tR\x06origin\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12\x1f\n" +
	"\vdistance_km\x18\x03 \x01(\x05R\n" +
	"distanceKm\x126\n" +
	"\x17estimated_duration_mins\x18\x04 \x01(\x05R\x15estimatedDurationMins\"A\n" +
	"\x11ListRoutesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"B\n" +
	"\x12ListRoutesResponse\x12,\n" +
	"\x06routes\x18\x01 \x03(\v2\x14.fleet.RouteResponseR\x06routes\"\xcc\x01\n" +
	"\x10ScheduleResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\broute_id\x18\x02 \x01(\tR\arouteId\x12\x15\n" +
	"\x06bus_id\x18\x03 \x01(\tR\x05busId\x12%\n" +
	"\x0edeparture_time\x18\x04 \x01(\tR\rdepartureTime\x12!\n" +
	"\farrival_time\x18\x05 \x01(\tR\varrivalTime\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\"\xc1\x01\n" +
	"\x15CreateScheduleRequest\x12\x19\n" +
	"\broute_id\x18\x01 \x01(\tR\arouteId\x12\x15\n" +
	"\x06bus_id\x18\x02 \x01(\tR\x05busId\x12%\n" +
	"\x0edeparture_time\x18\x03 \x01(\tR\rdepartureTime\x12!\n" +
	"\farrival_time\x18\x04 \x01(\tR\varrivalTime\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"D\n" +
	"\x14ListSchedulesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"N\n" +
	"\x15ListSchedulesResponse\x125\n" +
	"\tschedules\x18\x01 \x03(\v2\x17.fleet.ScheduleResponseR\tschedules\"\x94\x01\n" +
	"\x12SeatLayoutResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06bus_id\x18\x02 \x01(\tR\x05busId\x12\x1f\n" +
	"\vseat_number\x18\x03 \x01(\tR\n" +
	"seatNumber\x12\x1b\n" +
	"\tis_window\x18\x04 \x01(\bR\bisWindow\x12\x19\n" +
	"\bis_aisle\x18\x05 \x01(\bR\aisAisle\"\x89\x01\n" +
	"\x17CreateSeatLayoutRequest\x12\x15\n" +
	"\x06bus_id\x18\x01 \x01(\tR\x05busId\x12\x1f\n" +
	"\vseat_number\x18\x02 \x01(\tR\n" +
	"seatNumber\x12\x1b\n" +
	"\tis_window\x18\x03 \x01(\bR\bisWindow\x12\x19\n" +
	"\bis_aisle\x18\x04 \x01(\bR\aisAisle\",\n" +
	"\x13ListBusSeatsRequest\x12\x15\n" +
	"\x06bus_id\x18\x01 \x01(\tR\x05busId\"G\n" +
	"\x14ListBusSeatsResponse\x12/\n" +
	"\x05seats\x18\x01 \x03(\v2\x19.fleet.SeatLayoutResponseR\x05seats\"5\n" +
	"\x12GetManifestRequest\x12\x1f\n" +
	"\vschedule_id\x18\x01 \x01(\tR\n" +
	"scheduleId\"\xa1\x01\n" +
	"\x13GetManifestResponse\x12\x1f\n" +
	"\vschedule_id\x18\x01 \x01(\tR\n" +
	"scheduleId\x12#\n" +
	"\roperator_name\x18\x02 \x01(\tR\foperatorName\x12!\n" +
	"\fplate_number\x18\x03 \x01(\tR\vplateNumber\x12!\n" +
	"\fbooked_seats\x18\x04 \x03(\tR\vbookedSeats2\xfe\x04\n" +
	"\fFleetService\x128\n" +
	"\tCreateBus\x12\x17.fleet.CreateBusRequest\x1a\x12.fleet.BusResponse\x12>\n" +
	"\tListBuses\x12\x17.fleet.ListBusesRequest\x1a\x18.fleet.ListBusesResponse\x12>\n" +
	"\vCreateRoute\x12\x19.fleet.CreateRouteRequest\x1a\x14.fleet.RouteResponse\x12A\n" +
	"\n" +
	"ListRoutes\x12\x18.fleet.ListRoutesRequest\x1a\x19.fleet.ListRoutesResponse\x12G\n" +
	"\x0eCreateSchedule\x12\x1c.fleet.CreateScheduleRequest\x1a\x17.fleet.ScheduleResponse\x12J\n" +
	"\rListSchedules\x12\x1b.fleet.ListSchedulesRequest\x1a\x1c.fleet.ListSchedulesResponse\x12M\n" +
	"\x10CreateSeatLayout\x12\x1e.fleet.CreateSeatLayoutRequest\x1a\x19.fleet.SeatLayoutResponse\x12G\n" +
	"\fListBusSeats\x12\x1a.fleet.ListBusSeatsRequest\x1a\x1b.fleet.ListBusSeatsResponse\x12D\n" +
	"\vGetManifest\x12\x19.fleet.GetManifestRequest\x1a\x1a.fleet.GetManifestResponseB1Z/github.com/biruk/bus-ticket/fleet-service/protob\x06proto3"

var (
	file_fleet_proto_rawDescOnce sync.Once
	file_fleet_proto_rawDescData []byte
)

func file_fleet_proto_rawDescGZIP() []byte {
	file_fleet_proto_rawDescOnce.Do(func() {
		file_fleet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fleet_proto_rawDesc), len(file_fleet_proto_rawDesc)))
	})
	return file_fleet_proto_rawDescData
}

var file_fleet_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_fleet_proto_goTypes = []any{
	(*BusResponse)(nil),             // 0: fleet.BusResponse
	(*CreateBusRequest)(nil),        // 1: fleet.CreateBusRequest
	(*ListBusesRequest)(nil),        // 2: fleet.ListBusesRequest
	(*ListBusesResponse)(nil),       // 3: fleet.ListBusesResponse
	(*RouteResponse)(nil),           // 4: fleet.RouteResponse
	(*CreateRouteRequest)(nil),      // 5: fleet.CreateRouteRequest
	(*ListRoutesRequest)(nil),       // 6: fleet.ListRoutesRequest
	(*ListRoutesResponse)(nil),      // 7: fleet.ListRoutesResponse
	(*ScheduleResponse)(nil),        // 8: fleet.ScheduleResponse
	(*CreateScheduleRequest)(nil),   // 9: fleet.CreateScheduleRequest
	(*ListSchedulesRequest)(nil),    // 10: fleet.ListSchedulesRequest
	(*ListSchedulesResponse)(nil),   // 11: fleet.ListSchedulesResponse
	(*SeatLayoutResponse)(nil),      // 12: fleet.SeatLayoutResponse
	(*CreateSeatLayoutRequest)(nil), // 13: fleet.CreateSeatLayoutRequest
	(*ListBusSeatsRequest)(nil),     // 14: fleet.ListBusSeatsRequest
	(*ListBusSeatsResponse)(nil),    // 15: fleet.ListBusSeatsResponse
	(*GetManifestRequest)(nil),      // 16: fleet.GetManifestRequest
	(*GetManifestResponse)(nil),     // 17: fleet.GetManifestResponse
}
var file_fleet_proto_depIdxs = []int32{
	0,  // 0: fleet.ListBusesResponse.buses:type_name -> fleet.BusResponse
	4,  // 1: fleet.ListRoutesResponse.routes:type_name -> fleet.RouteResponse
	8,  // 2: fleet.ListSchedulesResponse.schedules:type_name -> fleet.ScheduleResponse
	12, // 3: fleet.ListBusSeatsResponse.seats:type_name -> fleet.SeatLayoutResponse
	1,  // 4: fleet.FleetService.CreateBus:input_type -> fleet.CreateBusRequest
	2,  // 5: fleet.FleetService.ListBuses:input_type -> fleet.ListBusesRequest
	5,  // 6: fleet.FleetService.CreateRoute:input_type -> fleet.CreateRouteRequest
	6,  // 7: fleet.FleetService.ListRoutes:input_type -> fleet.ListRoutesRequest
	9,  // 8: fleet.FleetService.CreateSchedule:input_type -> fleet.CreateScheduleRequest
	10, // 9: fleet.FleetService.ListSchedules:input_type -> fleet.ListSchedulesRequest
	13, // 10: fleet.FleetService.CreateSeatLayout:input_type -> fleet.CreateSeatLayoutRequest
	14, // 11: fleet.FleetService.ListBusSeats:input_type -> fleet.ListBusSeatsRequest
	16, // 12: fleet.FleetService.GetManifest:input_type -> fleet.GetManifestRequest
	0,  // 13: fleet.FleetService.CreateBus:output_type -> fleet.BusResponse
	3,  // 14: fleet.FleetService.ListBuses:output_type -> fleet.ListBusesResponse
	4,  // 15: fleet.FleetService.CreateRoute:output_type -> fleet.RouteResponse
	7,  // 16: fleet.FleetService.ListRoutes:output_type -> fleet.ListRoutesResponse
	8,  // 17: fleet.FleetService.CreateSchedule:output_type -> fleet.ScheduleResponse
	11, // 18: fleet.FleetService.ListSchedules:output_type -> fleet.ListSchedulesResponse
	12, // 19: fleet.FleetService.CreateSeatLayout:output_type -> fleet.SeatLayoutResponse
	15, // 20: fleet.FleetService.ListBusSeats:output_type -> fleet.ListBusSeatsResponse
	17, // 21: fleet.FleetService.GetManifest:output_type -> fleet.GetManifestResponse
	13, // [13:22] is the sub-list for method output_type
	4,  // [4:13] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_fleet_proto_init() }
func file_fleet_proto_init() {
	if File_fleet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fleet_proto_rawDesc), len(file_fleet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fleet_proto_goTypes,
		DependencyIndexes: file_fleet_proto_depIdxs,
		MessageInfos:      file_fleet_proto_msgTypes,
	}.Build()
	File_fleet_proto = out.File
	file_fleet_proto_goTypes = nil
	file_fleet_proto_depIdxs = nil
}
