// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: fleet.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBus = `-- name: CreateBus :one
INSERT INTO buses (
    plate_number, operator_name, capacity
) VALUES (
    $1, $2, $3
) RETURNING id, plate_number, operator_name, capacity, created_at, updated_at
`

type CreateBusParams struct {
	PlateNumber  string
	OperatorName string
	Capacity     int32
}

func (q *Queries) CreateBus(ctx context.Context, arg CreateBusParams) (Bus, error) {
	row := q.db.QueryRow(ctx, createBus, arg.PlateNumber, arg.OperatorName, arg.Capacity)
	var i Bus
	err := row.Scan(
		&i.ID,
		&i.PlateNumber,
		&i.OperatorName,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRoute = `-- name: CreateRoute :one
INSERT INTO routes (
    origin, destination, distance_km, estimated_duration_mins
) VALUES (
    $1, $2, $3, $4
) RETURNING id, origin, destination, distance_km, estimated_duration_mins, created_at, updated_at
`

type CreateRouteParams struct {
	Origin                string
	Destination           string
	DistanceKm            int32
	EstimatedDurationMins int32
}

func (q *Queries) CreateRoute(ctx context.Context, arg CreateRouteParams) (Route, error) {
	row := q.db.QueryRow(ctx, createRoute,
		arg.Origin,
		arg.Destination,
		arg.DistanceKm,
		arg.EstimatedDurationMins,
	)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.Origin,
		&i.Destination,
		&i.DistanceKm,
		&i.EstimatedDurationMins,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSchedule = `-- name: CreateSchedule :one
INSERT INTO schedules (
    route_id, bus_id, departure_time, arrival_time, price, status
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, route_id, bus_id, departure_time, arrival_time, price, status, created_at, updated_at
`

type CreateScheduleParams struct {
	RouteID       pgtype.UUID
	BusID         pgtype.UUID
	DepartureTime pgtype.Timestamptz
	ArrivalTime   pgtype.Timestamptz
	Price         pgtype.Numeric
	Status        string
}

func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, createSchedule,
		arg.RouteID,
		arg.BusID,
		arg.DepartureTime,
		arg.ArrivalTime,
		arg.Price,
		arg.Status,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.RouteID,
		&i.BusID,
		&i.DepartureTime,
		&i.ArrivalTime,
		&i.Price,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSeatLayout = `-- name: CreateSeatLayout :one
INSERT INTO seat_layouts (
    bus_id, seat_number, is_window, is_aisle
) VALUES (
    $1, $2, $3, $4
) RETURNING id, bus_id, seat_number, is_window, is_aisle, created_at
`

type CreateSeatLayoutParams struct {
	BusID      pgtype.UUID
	SeatNumber string
	IsWindow   bool
	IsAisle    bool
}

func (q *Queries) CreateSeatLayout(ctx context.Context, arg CreateSeatLayoutParams) (SeatLayout, error) {
	row := q.db.QueryRow(ctx, createSeatLayout,
		arg.BusID,
		arg.SeatNumber,
		arg.IsWindow,
		arg.IsAisle,
	)
	var i SeatLayout
	err := row.Scan(
		&i.ID,
		&i.BusID,
		&i.SeatNumber,
		&i.IsWindow,
		&i.IsAisle,
		&i.CreatedAt,
	)
	return i, err
}

const getBus = `-- name: GetBus :one
SELECT id, plate_number, operator_name, capacity, created_at, updated_at FROM buses
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetBus(ctx context.Context, id pgtype.UUID) (Bus, error) {
	row := q.db.QueryRow(ctx, getBus, id)
	var i Bus
	err := row.Scan(
		&i.ID,
		&i.PlateNumber,
		&i.OperatorName,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoute = `-- name: GetRoute :one
SELECT id, origin, destination, distance_km, estimated_duration_mins, created_at, updated_at FROM routes
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRoute(ctx context.Context, id pgtype.UUID) (Route, error) {
	row := q.db.QueryRow(ctx, getRoute, id)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.Origin,
		&i.Destination,
		&i.DistanceKm,
		&i.EstimatedDurationMins,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSchedule = `-- name: GetSchedule :one
SELECT id, route_id, bus_id, departure_time, arrival_time, price, status, created_at, updated_at FROM schedules
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSchedule(ctx context.Context, id pgtype.UUID) (Schedule, error) {
	row := q.db.QueryRow(ctx, getSchedule, id)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.RouteID,
		&i.BusID,
		&i.DepartureTime,
		&i.ArrivalTime,
		&i.Price,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBusSeats = `-- name: ListBusSeats :many
SELECT id, bus_id, seat_number, is_window, is_aisle, created_at FROM seat_layouts
WHERE bus_id = $1
`

func (q *Queries) ListBusSeats(ctx context.Context, busID pgtype.UUID) ([]SeatLayout, error) {
	rows, err := q.db.Query(ctx, listBusSeats, busID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SeatLayout
	for rows.Next() {
		var i SeatLayout
		if err := rows.Scan(
			&i.ID,
			&i.BusID,
			&i.SeatNumber,
			&i.IsWindow,
			&i.IsAisle,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBuses = `-- name: ListBuses :many
SELECT id, plate_number, operator_name, capacity, created_at, updated_at FROM buses
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListBusesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListBuses(ctx context.Context, arg ListBusesParams) ([]Bus, error) {
	rows, err := q.db.Query(ctx, listBuses, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bus
	for rows.Next() {
		var i Bus
		if err := rows.Scan(
			&i.ID,
			&i.PlateNumber,
			&i.OperatorName,
			&i.Capacity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutes = `-- name: ListRoutes :many
SELECT id, origin, destination, distance_km, estimated_duration_mins, created_at, updated_at FROM routes
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListRoutesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListRoutes(ctx context.Context, arg ListRoutesParams) ([]Route, error) {
	rows, err := q.db.Query(ctx, listRoutes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Route
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.Origin,
			&i.Destination,
			&i.DistanceKm,
			&i.EstimatedDurationMins,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedules = `-- name: ListSchedules :many
SELECT id, route_id, bus_id, departure_time, arrival_time, price, status, created_at, updated_at FROM schedules
ORDER BY departure_time ASC
LIMIT $1 OFFSET $2
`

type ListSchedulesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListSchedules(ctx context.Context, arg ListSchedulesParams) ([]Schedule, error) {
	rows, err := q.db.Query(ctx, listSchedules, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Schedule
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.RouteID,
			&i.BusID,
			&i.DepartureTime,
			&i.ArrivalTime,
			&i.Price,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
