// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Bus struct {
	ID           pgtype.UUID
	PlateNumber  string
	OperatorName string
	Capacity     int32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Route struct {
	ID                    pgtype.UUID
	Origin                string
	Destination           string
	DistanceKm            int32
	EstimatedDurationMins int32
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type Schedule struct {
	ID            pgtype.UUID
	RouteID       pgtype.UUID
	BusID         pgtype.UUID
	DepartureTime pgtype.Timestamptz
	ArrivalTime   pgtype.Timestamptz
	Price         pgtype.Numeric
	Status        string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type SeatLayout struct {
	ID         pgtype.UUID
	BusID      pgtype.UUID
	SeatNumber string
	IsWindow   bool
	IsAisle    bool
	CreatedAt  pgtype.Timestamptz
}
