// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Transaction struct {
	ID             pgtype.UUID
	BookingID      pgtype.UUID
	UserID         pgtype.UUID
	Amount         pgtype.Numeric
	StripeIntentID string
	Status         string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}
