// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: transactions.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    booking_id, user_id, amount, stripe_intent_id, status
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, booking_id, user_id, amount, stripe_intent_id, status, created_at, updated_at
`

type CreateTransactionParams struct {
	BookingID      pgtype.UUID
	UserID         pgtype.UUID
	Amount         pgtype.Numeric
	StripeIntentID string
	Status         string
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.BookingID,
		arg.UserID,
		arg.Amount,
		arg.StripeIntentID,
		arg.Status,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.UserID,
		&i.Amount,
		&i.StripeIntentID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTransactionStatusByIntent = `-- name: UpdateTransactionStatusByIntent :one
UPDATE transactions 
SET status = $2, updated_at = CURRENT_TIMESTAMP
WHERE stripe_intent_id = $1 RETURNING id, booking_id, user_id, amount, stripe_intent_id, status, created_at, updated_at
`

type UpdateTransactionStatusByIntentParams struct {
	StripeIntentID string
	Status         string
}

func (q *Queries) UpdateTransactionStatusByIntent(ctx context.Context, arg UpdateTransactionStatusByIntentParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransactionStatusByIntent, arg.StripeIntentID, arg.Status)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.UserID,
		&i.Amount,
		&i.StripeIntentID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
