// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: booking.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (
    user_id, schedule_id, seat_number, status, price
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, user_id, schedule_id, seat_number, status, price, created_at, updated_at
`

type CreateBookingParams struct {
	UserID     pgtype.UUID
	ScheduleID pgtype.UUID
	SeatNumber string
	Status     string
	Price      pgtype.Numeric
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.UserID,
		arg.ScheduleID,
		arg.SeatNumber,
		arg.Status,
		arg.Price,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ScheduleID,
		&i.SeatNumber,
		&i.Status,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserBookings = `-- name: ListUserBookings :many
SELECT id, user_id, schedule_id, seat_number, status, price, created_at, updated_at FROM bookings
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUserBookingsParams struct {
	UserID pgtype.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListUserBookings(ctx context.Context, arg ListUserBookingsParams) ([]Booking, error) {
	rows, err := q.db.Query(ctx, listUserBookings, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ScheduleID,
			&i.SeatNumber,
			&i.Status,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBookingStatus = `-- name: UpdateBookingStatus :one
UPDATE bookings 
SET status = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 RETURNING id, user_id, schedule_id, seat_number, status, price, created_at, updated_at
`

type UpdateBookingStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) (Booking, error) {
	row := q.db.QueryRow(ctx, updateBookingStatus, arg.ID, arg.Status)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ScheduleID,
		&i.SeatNumber,
		&i.Status,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
