// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Booking struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	ScheduleID pgtype.UUID
	SeatNumber string
	Status     string
	Price      pgtype.Numeric
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}
